
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fd
  annotations:
    kubernetes.io/change-cause: " my custom " 
  labels:
    name: fd
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
      name: fp
    spec:
      containers:
      - name: ngnix
        image: nginx

