apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"kubernetes.io/change-cause":" my custom "},"labels":{"name":"fd"},"name":"fd","namespace":"default"},"spec":{"replicas":5,"selector":{"matchLabels":{"app":"myapp"}},"template":{"metadata":{"labels":{"app":"myapp"},"name":"fp"},"spec":{"containers":[{"image":"nginx","name":"ngnix"}]}}}}
  creationTimestamp: "2021-01-14T12:53:48Z"
  generation: 9
  labels:
    name: fd
  name: fd
  namespace: default
  resourceVersion: "58838"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/fd
  uid: 8b96ea37-5667-11eb-b768-0e3f56811d5d
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: myapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapp
      name: fp
    spec:
      containers:
      - image: coolgourav147/nginx-custom:v2
        imagePullPolicy: IfNotPresent
        name: ngnix
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
  conditions:
  - lastTransitionTime: "2021-01-14T12:53:50Z"
    lastUpdateTime: "2021-01-14T12:53:50Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-01-14T13:35:56Z"
    lastUpdateTime: "2021-01-14T13:35:56Z"
    message: ReplicaSet "fd-6dbbf694d9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 9
  readyReplicas: 5
  replicas: 5
  updatedReplicas: 5
