apiVersion: v1
kind: Pod

metadata:
  labels:
    podname: fp1
    app: myapp
  name: wbedefault
spec:
  containers:
  - name: ngnix
    image: coolgourav147/nginx-custom
    env: 
    - name: name 
      value: aj
    - name: city 
      value: bn 
