apiVersion: v1
kind: Pod

metadata:
  labels:
    podname: fp1
  name: fp
spec:
  containers:
  - name: ngnix
    image: coolgourav147/nginx-custom:v2
    resources:
      requests:
        memory: 2Gi

