
apiVersion: v1
kind: Pod

metadata:
  labels:
    app: myapp
  name: wbedefault
spec:
  containers:
  - name: ngnix
    image: coolgourav147/nginx-custom
  tolerations:
  -  key: ""
     effect: ""
     operator: "Exists"
     value: ""

