
apiVersion: v1

kind: Service

metadata:
  name: myfirstser
  labels:
    servicelabel: labname

spec:
  type: NodePort
  ports:
    - nodePort: 32000
      port: 9000
      targetPort: 80
  selector:
    type: app

