apiVersion: v1
kind: Pod

metadata:
  labels:
    app: myapp
  name: pod

spec:
  containers:
  - name: ngnix
    image: coolgourav147/nginx-custom
    envFrom:
    - configMapRef:
        name: cm11

