
apiVersion: v1
kind: Pod

metadata:
  name: pod4
  labels:
    app: myapp1
    type: frontend

spec:
  containers:
  - name: mycont
    image: coolgourav147/nginx-custom
    resources:
      requests:
        memory: 200Mi
        cpu: 0.1
      limits:
        memory: 2500Mi
        cpu: .5

