

apiVersion: v1
kind: Pod

metadata:
  labels:
    app: myapp
  name: wbedefault

spec:
  containers:
  - name: ngnix
    image: coolgourav147/nginx-custom
    env:
    - name: ip
      valueFrom:
        configMapKeyRef:
          key: database_ip
          name: cm11

